'use client';
import {BrandLogo} from './service-links';
import {useState,type ReactNode} from 'react';
import {Download,ArrowUpRight} from 'lucide-react';
import {formCode,webCode,htmlCode} from './script-examples';
import {designs} from './workshop';
import {saveText} from './charts';
export function AppsScriptLab({mode,index,prompt}:{mode:string;index:number;prompt:(title:string,body:string)=>ReactNode}){const [rows,setRows]=useState<{id:string;week:string;emotion:string;score:string}[]>([]);const [message,setMessage]=useState('');const d=designs[index];
 const p=`연구주제: ${d.short}\n질문: ${d.question}\n수집 단위: ${d.unit}\n검토할 열: ${d.fields}\nGoogle 스프레드시트의 확장 프로그램 > Apps Script에서 실행할 데이터 수집 도구를 만들어줘. 우선 연구 질문에 꼭 필요한 문항만 제안하고, 각 문항의 변수명·자료형·범위·필수여부를 표로 설명해줘. 검증된 척도 문항을 임의로 만들지 말고 자체 문항은 연수용 초안으로 표시해줘. 실제 학생 이름·이메일·민감한 자유서술은 수집하지 않고 가상ID를 사용해.\n${mode==='구글폼 만들기'?'Code.gs에서 FormApp으로 게시 전 초안 폼을 만들고 현재 스프레드시트에 응답을 연결해줘. 함수 재실행으로 폼이 계속 만들어지지 않게 ID를 저장해줘. 문항 유효성 검사와 선택 응답을 구분해줘. 실행 로그에는 폼 편집 주소와 응답 주소를 출력해줘. 폼 게시·응답자 설정은 사용자가 직접 확인하게 안내해줘. 웹앱 배포는 필요 없어.':'Code.gs와 Index.html을 별도 코드블록으로 줘. setup에서 연결된 시트ID를 ScriptProperties에 저장하고, doGet으로 HTML을 반환해줘. google.script.run으로 서버에 전달하고 서버가 자료형·범위·허용값을 다시 검사하게 해줘. LockService와 요청ID로 동시 제출과 같은 요청의 중복 저장을 처리해줘. 빈 점수는 0이 아니라 빈칸으로 저장하고, 자유문자열은 시트 수식으로 실행되지 않게 해줘. 성공과 실패를 모두 화면에 보여줘. 학생에게 시트 전체를 공유하지 말고 학교 계정 범위로 웹앱 접근을 설정하는 배포 순서를 알려줘.'}\n마지막에 정상 1건·빈 입력·범위 밖 값·중복 제출의 테스트표, 권한 오류 시 확인할 점, CSV로 내려받아 대시보드에 연결하는 방법을 써줘. 코드를 실제 실행했다고 말하지 마.`;
 return mode==='수집 화면 체험'?<div className='split'><div className='panel'><span className='eyebrow'>미리 눌러보기 · GOOGLE 연결 없음</span><h3>오늘의 마음 체크인</h3><p>가상 응답을 넣으면 오른쪽 표에 한 행씩 쌓입니다. 실제 Apps Script 예제도 이 흐름으로 작동하도록 작성했습니다.</p><form className='demo-form' onSubmit={e=>{e.preventDefault();const f=e.currentTarget;const v=Object.fromEntries(new FormData(f));setRows([...rows,{id:String(v.id),week:String(v.week),emotion:String(v.emotion),score:String(v.score)}]);setMessage('체험 표에 저장했습니다. 구글 시트에는 전송하지 않았습니다.');f.reset()}}><label>가상ID<input name='id' placeholder='S01' pattern='S[0-9]{2}' maxLength={3} required/></label><label>주차<select name='week'>{[1,2,3,4,5,6].map(x=><option key={x}>{x}</option>)}</select></label><label>감정<select name='emotion' required><option value=''>선택하세요</option>{['편안','기쁨','걱정','속상','말하고 싶지 않음'].map(x=><option key={x}>{x}</option>)}</select></label><label>편안함 (1–5, 선택)<select name='score'><option value=''>미응답</option>{[1,2,3,4,5].map(x=><option key={x}>{x}</option>)}</select></label><button className='btn primary' type='submit'>가상 응답 저장</button></form><small role='status'>{message}</small></div><div className='panel tinted'><h3>쌓이는 데이터 · {rows.length}행</h3><div className='demo-results'><table><thead><tr><th>ID</th><th>주차</th><th>감정</th><th>점수</th></tr></thead><tbody>{rows.map((r,i)=><tr key={i}><td>{r.id}</td><td>{r.week}</td><td>{r.emotion}</td><td>{r.score||'미응답'}</td></tr>)}</tbody></table>{rows.length===0&&<p>왼쪽에 가상 응답을 넣어보세요.</p>}</div><button className='btn' disabled={!rows.length} onClick={()=>saveText(['data_origin,student_id,week,emotion,score',...rows.map(r=>`synthetic,${r.id},${r.week},${r.emotion},${r.score}`)].join('\n'),'체험-응답-synthetic.csv','text/csv;charset=utf-8')}><Download size={16}/> 이 표를 CSV로</button><div className='callout'>이 체험은 화면을 떠나면 초기화됩니다. 실제 수집은 구글폼 또는 배포한 Apps Script 웹앱에서 진행합니다.</div></div></div>:<div className='split'><div className='panel'><span className='eyebrow'>{mode==='구글폼 만들기'?'기본 실습 · 12분':'확장 자료 · 연수 후 실습'}</span><h2>{mode==='구글폼 만들기'?'Code.gs로 폼 만들기':'입력 화면을 웹앱으로 배포'}</h2>{(mode==='구글폼 만들기'?[
 ['01','새 스프레드시트 → Apps Script','확장 프로그램 > Apps Script를 엽니다. 예제 Code.gs를 붙여넣고 저장합니다.'],
 ['02','createPracticeForm 실행','함수를 선택해 실행합니다. 본인이 작성한 코드와 요청 권한을 확인하고 진행합니다. 기관에서 차단하면 관리자에게 확인합니다.'],
 ['03','실행 로그의 폼 편집 주소 열기','문항과 필수 여부, 이메일 수집, 응답자 접근 범위를 확인합니다. 폼 화면에서 게시한 뒤 응답 링크를 사용합니다.'],
 ['04','가상 응답 3건 → 시트 확인','S01·S02·S03으로 응답합니다. 연결된 시트의 응답 탭에서 열과 행을 확인하고 해당 탭을 CSV로 내려받습니다.'],
 ]:[
 ['01','Code.gs + Index.html 추가','새 시트의 Apps Script에 Code.gs를 넣고, + > HTML로 Index 파일을 만든 뒤 HTML 코드를 붙입니다.'],
 ['02','setup 실행 후 테스트','setup을 한 번 실행해 시트를 준비하고 권한을 확인합니다. doGet을 편집기에서 실행하는 것만으로 배포되지는 않습니다.'],
 ['03','배포 > 새 배포 > 웹 앱','교사 소유 시트에 저장하려면 실행 사용자를 본인으로 설정하고, 접근은 허용된 학교 계정 범위로 제한합니다. 선택지는 기관 정책에 따라 다릅니다.'],
 ['04','/exec 주소로 응답 확인','동료 계정에서 열어 제출하고 시트에서 확인합니다. 코드 수정 후 배포 관리에서 새 버전을 선택해야 /exec에 반영됩니다.'],
 ]).map(([n,t,b])=><div className='task' key={n}><span>{n}</span><div><h3>{t}</h3><p>{b}</p></div></div>)}<a className='btn' href={mode==='구글폼 만들기'?'https://developers.google.com/apps-script/reference/forms/form':'https://developers.google.com/apps-script/guides/web'} target='_blank' rel='noopener noreferrer'><BrandLogo brand='google'/>Google 공식 안내 <ArrowUpRight size={16}/></a><p className='small'>{mode==='구글폼 만들기'?'폼 생성 스크립트는 웹앱 배포가 필요 없습니다. 응답 링크와 편집 링크를 구분하세요.':'/dev는 편집자용 테스트 주소입니다. 학생에게 스프레드시트 전체를 공유할 필요는 없습니다.'}</p></div><div className='panel tinted'><h3>선택한 연구주제로 요청하기</h3><p className='small'>{d.short} · 이 주제에 맞는 문항과 수집 코드를 요청합니다.</p>{prompt('AI에게 코드 요청하기',p)}{prompt(mode==='구글폼 만들기'?'예제 Code.gs 펼치기':'예제 Code.gs · 서버',mode==='구글폼 만들기'?formCode:webCode)}{mode!=='구글폼 만들기'&&prompt('예제 Index.html · 입력 화면',htmlCode)}<div className='download-row'><button className='btn' onClick={()=>saveText(mode==='구글폼 만들기'?formCode:webCode,'Code.gs')}><Download size={16}/> Code.gs</button>{mode!=='구글폼 만들기'&&<button className='btn' onClick={()=>saveText(htmlCode,'Index.html','text/html;charset=utf-8')}><Download size={16}/> Index.html</button>}</div><div className='callout'>예제 문항은 가상 체크인 실습용이며 검증된 SEL 척도가 아닙니다. 실제 연구에서는 문항 출처·수집 근거·접근 권한을 먼저 정합니다.</div><h3>막히면 여기부터</h3><p className='small'>{mode==='구글폼 만들기'?'권한 오류 → 로그인 계정·기관 정책 확인. 응답이 안 쌓이면 폼의 응답 대상 시트를 확인. 게시 전에는 응답 링크가 열리지 않을 수 있습니다.':'Index를 찾을 수 없음 → HTML 파일명 확인. 저장 실패 → setup 실행·시트 존재·실행 권한 확인. 수정이 안 보임 → 배포 버전 갱신. 중복·빈값은 원자료에서 다시 점검.'}</p><small>Google 계정에서 직접 실행·확인해야 합니다. 이 페이지가 폼이나 웹앱을 자동 배포하지는 않습니다.</small></div></div>;
}
