'use client';
import {useState} from 'react';
import {ResponsiveContainer,BarChart,Bar,LineChart,Line,CartesianGrid,XAxis,YAxis,Tooltip,Legend,ScatterChart,Scatter,RadarChart,PolarGrid,PolarAngleAxis,PolarRadiusAxis,Radar,ReferenceLine} from 'recharts';
import {Download,Table2} from 'lucide-react';
import {MindDashboard} from './mind-dashboard';
import {instructorIndex} from './instructor-sample';
import {designs,chartNames,type ChartKind} from './workshop';

export function saveText(text:string,name:string,type='text/plain;charset=utf-8'){const url=URL.createObjectURL(new Blob(['\uFEFF'+text],{type}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
export function makeData(index:number,kind?:ChartKind){const d=designs[index],k=kind||d.chart;const n=k==='single'?12:k==='scatter'?12:d.labels.length;const span=d.range[1]-d.range[0];return Array.from({length:n},(_,i)=>{const pre=Math.round((d.range[0]+span*(.28+((i*7+index)%11)/28))*10)/10;const post=Math.min(d.range[1],Math.max(d.range[0],Math.round((pre+span*(i%5===0?-.12:.14))*10)/10));return {id:`S${String(i+1).padStart(2,'0')}`,label:d.labels[i%d.labels.length],before:k==='stacked'?4+i*2:pre,after:k==='stacked'?8-i:post,value:k==='single'?[8,9,7,10,8,9,6,7,4,5,3,4][i]:k==='funnel'?[100,84,66,54][i]:post,x:i+1};});}
const defaultEvidence=[['E01','“처음에는 막혔지만, 친구의 설명을 듣고 다시 해봤어요.”','다시 시도함','동료 설명이 재시도와 연결되었을 가능성','도움 없이도 시도했는지 확인'],['E02','“시간이 정해져 있어서 제 방식대로 하기 어려웠어요.”','선택의 제약','활동 구조가 일부 참여자의 자율성을 제한했을 가능성','구조가 도움이 된 반대 사례 찾기'],['E03','“다음 시간에는 방법을 바꿔보고 싶어요.”','수정 계획','다음 실행 의도가 드러남','계획이 실제 행동으로 이어졌는지 관찰']];
const experienceEvidence=[['E01','“알림이 안 와서 글을 끝까지 읽었어요.”','방해의 감소','기기 제한이 집중을 도왔을 가능성','읽기 과제나 장소의 영향도 확인'],['E02','“모르는 말을 찾아볼 수 없어 답답했어요.”','탐색 기회 제한','제한이 학습 전략의 선택을 막았을 가능성','사전·교사 질문 등 대안 사용 확인'],['E03','“친구와 이야기하는 시간은 더 많아졌어요.”','상호작용 변화','제한 뒤 또래 활동이 달라졌을 가능성','같은 제한에서 고립감을 느낀 반례 탐색']];
const communityEvidence=[['E01','“회의 시간을 정해두니 다음 수업까지 같이 준비했어요.”','공동 시간 확보','정기적인 시간이 공동 실행을 도왔을 가능성','시간이 있어도 멈춘 사례와 비교'],['E02','“자료는 많이 나눴지만 실제 수업은 그대로였어요.”','공유와 실행의 차이','자료 공유만으로 실천 변화가 일어나지 않음','수업 관찰·수정 기록과 대조'],['E03','“서로 수업을 본 뒤 질문 방식을 바꿨습니다.”','동료 관찰 피드백','구체적 피드백이 수업 수정과 연결될 가능성','수정 전후 수업 기록 확인']];
function GeneralDashboard({index,override}:{index:number;override?:ChartKind}){const d=designs[index],kind=override||d.chart;const evidence=index===8?experienceEvidence:index===20?communityEvidence:defaultEvidence;const [table,setTable]=useState(false);const [period,setPeriod]=useState('전체');const full=makeData(index,kind);const data=period==='앞부분'?full.slice(0,Math.ceil(full.length/2)):full;const color='#526585',light='#bdc7d7';const legendA=index===5?'플랫폼 A':index===17?'버전 1':'사전 / 초안';const legendB=index===5?'플랫폼 B':index===17?'버전 2':'사후 / 수정';const grid=<CartesianGrid vertical={false} stroke='#e9ecf0'/>;const y=<YAxis domain={d.range} width={35} tick={{fontSize:12}} axisLine={false} tickLine={false}/>;const x=<XAxis dataKey='label' tick={{fontSize:12}} axisLine={false} tickLine={false}/>;const tip=<Tooltip contentStyle={{borderRadius:8,borderColor:'#e1e5eb'}}/>;
 const heatcols=index===14?['1주','2주','3주']:index===13?['국어','도덕','체육']:index===15?['사례A','사례B','사례C']:['1회','2회','3회'];const heatval=(i:number,j:number)=>Math.round((d.range[0]+(d.range[1]-d.range[0])*((i*3+j*2+index)%9)/8)*10)/10;
 const csv=kind==='evidence'?['data_origin,근거ID,가상인용,코드,해석,추가확인',...evidence.map(r=>['synthetic',...r].map(v=>'"'+v.replaceAll('"','""')+'"').join(','))].join('\n'):kind==='heatmap'?['data_origin,항목,회차,값,지표',...data.flatMap((r,i)=>heatcols.map((c,j)=>`synthetic,${r.label},${c},${heatval(i,j)},${d.metric}`))].join('\n'):['data_origin,id,항목,사전또는A,사후또는B,표시값,x,지표',...data.map(r=>`synthetic,${r.id},${r.label},${r.before},${r.after},${r.value},${r.x},${d.metric}`)].join('\n');
 let chart;
 if(kind==='evidence')chart=<div className='evidence-table'><table><thead><tr>{['근거','가상 발화','해석 / 추가 확인'].map(x=><th key={x}>{x}</th>)}</tr></thead><tbody>{evidence.map(r=><tr key={r[0]}><td>{r[0]}<small>{r[2]}</small></td><td>{r[1]}</td><td>{r[3]}<small>{r[4]}</small></td></tr>)}</tbody></table></div>;
 else if(kind==='heatmap')chart=<div className='heatmap'><div/><>{heatcols.map(x=><b key={x}>{x}</b>)}</>{data.map((r,i)=><div className='heatrow' key={r.id}><span>{r.label}</span>{heatcols.map((c,j)=>{const v=heatval(i,j);return <div key={c} style={{background:`rgba(82,101,133,${.1+.7*(v-d.range[0])/(d.range[1]-d.range[0])})`,color:(v-d.range[0])/(d.range[1]-d.range[0])>.65?'white':'#373a46'}}>{v}</div>})}</div>)}</div>;
 else if(kind==='paired'){const pairs=[{time:'사전',...Object.fromEntries(data.map(r=>[r.id,r.before]))},{time:'사후',...Object.fromEntries(data.map(r=>[r.id,r.after]))}];chart=<ResponsiveContainer width='100%' height='100%'><LineChart data={pairs} margin={{left:5,right:40,top:20,bottom:12}}>{grid}<XAxis dataKey='time'/>{y}{tip}{data.map((r,i)=><Line key={r.id} dataKey={r.id} name={r.label} stroke={['#526585','#8e9caf','#a17569','#587d76','#847394','#8a824f'][i%6]} strokeWidth={2} dot={{r:4}}/>)}</LineChart></ResponsiveContainer>}
 else if(kind==='radar')chart=<ResponsiveContainer width='100%' height='100%'><RadarChart data={data} outerRadius='68%'><PolarGrid stroke='#dfe4eb'/><PolarAngleAxis dataKey='label' tick={{fontSize:13}}/><PolarRadiusAxis domain={d.range} tickCount={4}/><Radar dataKey='before' name={legendA} stroke={light} fill={light} fillOpacity={.15}/><Radar dataKey='after' name={legendB} stroke={color} fill={color} fillOpacity={.15}/>{tip}<Legend/></RadarChart></ResponsiveContainer>;
 else if(kind==='scatter')chart=<ResponsiveContainer width='100%' height='100%'><ScatterChart margin={{bottom:15,right:20,top:10}}>{grid}<XAxis dataKey='x' type='number' name='전략사용 수' label={{value:'전략사용 수 (회)',position:'insideBottom',offset:-8}}/><YAxis dataKey='y' name={d.metric} type='number' domain={d.range} width={35}/>{tip}<Scatter data={data.map(r=>({...r,y:r.after}))} fill={color}/></ScatterChart></ResponsiveContainer>;
 else if(kind==='line'||kind==='single')chart=<ResponsiveContainer width='100%' height='100%'><LineChart data={data} margin={{right:25,top:20,bottom:10}}>{grid}{x}{y}{tip}{kind==='single'&&<ReferenceLine x='6' stroke='#a17569' strokeDasharray='5 4' label={{value:'기초선 | 중재',position:'insideTopRight',fontSize:12}}/>}<Line dataKey='value' name={d.metric} stroke={color} strokeWidth={2.5} dot={{r:4}}/></LineChart></ResponsiveContainer>;
 else chart=<ResponsiveContainer width='100%' height='100%'><BarChart data={data} layout={kind==='funnel'?'vertical':'horizontal'} margin={{right:25,top:15,bottom:10}}>{grid}{kind==='funnel'?<><XAxis type='number' domain={[0,100]}/><YAxis type='category' dataKey='label' width={80}/></>:<>{x}{kind==='stacked'?<YAxis width={35} domain={[0,20]}/>:y}</>}{tip}{kind==='funnel'?<Bar dataKey='value' name={d.metric} fill={color} radius={[0,4,4,0]}/>:<><Bar dataKey='before' stackId={kind==='stacked'?'a':undefined} name={kind==='stacked'?'근거 있음':legendA} fill={light} radius={[3,3,0,0]}/><Bar dataKey='after' stackId={kind==='stacked'?'a':undefined} name={kind==='stacked'?'근거 없음':legendB} fill={color} radius={[3,3,0,0]}/><Legend/></>}</BarChart></ResponsiveContainer>;
 return <div className='dashboard'><div className='dash-head'><div><span className='eyebrow'>가상 데이터 · 실제 연구 결과 아님</span><h3>{d.short}</h3></div><span className='tag'>{chartNames[kind]}</span></div><div className='metric-row'><div><small>관찰할 지표</small><b>{d.metric}</b></div><div><small>{kind==='evidence'?'가상 근거':kind==='heatmap'?'항목 수':'표시 단위 수'}</small><b>{kind==='evidence'?3:data.length}<em>개</em></b></div><div><small>자료 성격</small><b>연수용 예시</b></div></div><div className='chart-area' role='img' aria-label={`${d.short} ${chartNames[kind]} 가상 데이터 예시`}>{chart}</div><div className='dash-bottom'><span>{kind==='single'?'각 회기 20분 관찰 · A–B만으로 인과 추론 불가':kind==='funnel'?'시작 100명/세션 기준 · 학습 성과와 구분':kind==='evidence'?'인용은 모두 창작한 예시입니다.':`척도 ${d.range.join('–')} · 결측 없는 정리된 예시`}</span><button onClick={()=>setTable(!table)}><Table2 size={15}/> {table?'표 닫기':'수치 보기'}</button><button onClick={()=>saveText(csv,`topic-${index+1}-${kind}-synthetic.csv`,'text/csv;charset=utf-8')}><Download size={15}/> CSV</button></div>{table&&<div className='raw-table'><label>표시 범위 <select value={period} onChange={e=>setPeriod(e.target.value)}><option>전체</option><option>앞부분</option></select></label><pre>{csv}</pre></div>}</div>;
}

export function Dashboard(props:{index:number;override?:ChartKind}){return props.index===instructorIndex&&!props.override?<MindDashboard/>:<GeneralDashboard {...props}/>;}
