'use client';
import {useState} from 'react';
import {ArrowLeft,ArrowRight,ArrowUpRight} from 'lucide-react';
import {BrandLogo} from './service-links';
import {Prompt} from './practice-prompt';
const steps=[
 {title:'저장소 만들기',time:'3분',body:'GitHub에 로그인한 뒤 New repository를 누릅니다. 이름은 research-practice처럼 정하고, 연수용 가상 자료만 담을 Public 저장소를 만듭니다. Add README를 켜고 Create repository를 누르세요.',check:'무료 계정의 Pages 실습은 공개 저장소를 사용합니다. 실제 학생 자료와 API 키는 올리지 않습니다.'},
 {title:'index.html 올리기',time:'4분',body:'Claude에서 완성한 코드를 index.html로 저장합니다. 저장소의 Add file → Upload files에서 파일을 올리고 Commit changes를 누르세요. 파일이 폴더 안에 들어가지 않고 저장소 첫 화면에 보여야 합니다.',check:'파일 이름은 소문자 index.html입니다. index.html.txt나 JSX 소스 파일만 올리면 이 방식으로 실행되지 않습니다.'},
 {title:'Pages 켜기',time:'3분',body:'저장소의 Settings → Pages → Build and deployment로 갑니다. Source에서 Deploy from a branch를 고르고, Branch는 main, 폴더는 /(root)로 선택한 뒤 Save를 누릅니다.',check:'이 과정은 빌드가 필요 없는 HTML 파일 기준입니다. React 프로젝트는 먼저 빌드하거나 GitHub Actions 배포 구성이 필요합니다.'},
 {title:'주소 열고 확인하기',time:'7분',body:'배포가 끝나면 Settings → Pages의 Visit site를 누릅니다. 그 주소를 동료에게 보내 버튼·계산·작은 화면을 확인하고, 수정한 파일을 다시 올립니다. 확인된 웹앱 주소를 패들렛에 남겨주세요.',check:'배포 반영에는 최대 10분 정도 걸릴 수 있습니다. 기다리는 동안 동료 검토와 보고서 기록을 진행하세요. 404라면 Actions 실행 결과, main·/(root) 설정, index.html 위치부터 확인합니다.'}
];
export const githubExportPrompt='현재 만든 대시보드와 수업 웹앱을 GitHub Pages에서 실행할 수 있는 단일 index.html로 정리해줘. HTML·CSS·JavaScript를 한 파일에 넣고 빌드나 서버 없이 실행되게 해줘. JSX·TypeScript·Node.js·서버 API 의존성은 브라우저에서 실행되는 코드로 바꿔줘. AI API 키와 실제 학생 정보는 넣지 마. 가상 데이터 표시, 차트·집계표·필터·CSV 내려받기·입력 검증은 유지해줘. 외부 자산이 필요하면 용도를 설명하고, 로컬 자산 경로는 ./로 시작하는 상대경로를 써줘. 새로고침에도 작동하게 해시나 화면 전환 버튼을 사용해줘. 생략 없는 전체 index.html과 저장 방법, 기능별 확인표를 출력해줘. GitHub main 브랜치의 /(root)에서 배포할 예정이야. 실제 배포했다고 말하지 마.';
export function GitHubPublishLab(){const [step,setStep]=useState(0);const current=steps[step];return <div className='github-lab'><div className='section-row'><h3><BrandLogo brand='github'/> GitHub Pages 배포</h3><a className='btn' href='https://github.com/' target='_blank' rel='noopener noreferrer'><BrandLogo brand='github'/>GitHub 열기<ArrowUpRight size={15}/></a></div><div className='github-steps' aria-label='GitHub 배포 순서'>{steps.map((s,i)=><button key={s.title} aria-current={step===i?'step':undefined} onClick={()=>setStep(i)}>{i+1}. {s.title}</button>)}</div><div className='github-step'><span className='eyebrow'>{step+1} / 4 · {current.time}</span><h3>{current.title}</h3><p>{current.body}</p><div className='callout'>{current.check}</div></div><div className='section-row'><button className='btn' disabled={step===0} onClick={()=>setStep(step-1)}><ArrowLeft size={15}/>이전 단계</button><button className='btn' disabled={step===3} onClick={()=>setStep(step+1)}>다음 단계<ArrowRight size={15}/></button></div><Prompt title='GitHub 배포용 파일로 정리하기' body={githubExportPrompt}/><div className='source-links'><a href='https://docs.github.com/en/pages/getting-started-with-github-pages/creating-a-github-pages-site' target='_blank' rel='noopener noreferrer'><BrandLogo brand='github'/>사이트 만들기 · 공식 안내<ArrowUpRight size={14}/></a><a href='https://docs.github.com/en/pages/getting-started-with-github-pages/configuring-a-publishing-source-for-your-github-pages-site' target='_blank' rel='noopener noreferrer'>Pages 설정 · 공식 안내<ArrowUpRight size={14}/></a></div></div>;}
