'use client';
import {useEffect,useRef,useState,type ReactNode} from 'react';
import {motion,AnimatePresence,useReducedMotion} from 'motion/react';
import {ArrowLeft,ArrowRight,ArrowUpRight,BookOpen,Check,CheckCheck,ChevronDown,Clipboard,Download,ExternalLink,FileText,LayoutGrid,Link2,Pause,Play,RotateCcw,Search,Settings2,X} from 'lucide-react';
import {topics} from './data';
import {course,chapters,designs,references,prompts,chartNames,type ChartKind} from './workshop';
import {Dashboard,saveText} from './charts';
import {AppsScriptLab} from './apps-script-lab';
import {Prompt} from './practice-prompt';
import {ResearchPortal} from './research-portal';
import {GitHubPublishLab,githubExportPrompt} from './github-publish-lab';
import {BrandLogo,brandForUrl,PadletLink,PADLET_URL} from './service-links';

type Notes=Record<string,string>;
function Modal({title,onClose,children}:{title:string;onClose:()=>void;children:ReactNode}){const ref=useRef<HTMLDialogElement>(null);useEffect(()=>{ref.current?.showModal();return()=>ref.current?.close()},[]);return <dialog ref={ref} onCancel={onClose} className='modal'><header><h2>{title}</h2><button onClick={onClose} aria-label='닫기'><X size={22}/></button></header>{children}</dialog>}
function SourceLinks({ids}:{ids:string[]}){return <div className='source-links'>{ids.map(id=>{const r=references.find(x=>x.id===id)!;return <a href={r.url} target='_blank' rel='noreferrer' key={id}><BrandLogo brand={brandForUrl(r.url)}/>{r.title}<ArrowUpRight size={14}/></a>})}</div>}
function Task({n,title,children}:{n:string;title:string;children:ReactNode}){return <div className='task'><span>{n}</span><div><h3>{title}</h3><p>{children}</p></div></div>}
const gallery:{kind:ChartKind;index:number;use:string;avoid:string}[]=[{kind:'paired',index:1,use:'같은 학생의 사전·사후를 짝지어 볼 때',avoid:'평균 변화만으로 모두 좋아졌다고 쓰지 않기'},{kind:'bar',index:5,use:'동일 기준으로 도구·집단·시점을 비교할 때',avoid:'조건이 다른 플랫폼을 같은 순위로 묶지 않기'},{kind:'line',index:14,use:'시간의 흐름과 변화를 볼 때',avoid:'간격이 다른 날짜를 같은 간격으로 놓지 않기'},{kind:'heatmap',index:3,use:'여러 과제·시점에서 집중된 양상을 찾을 때',avoid:'색만 쓰지 말고 실제 값과 범위를 함께 표시'},{kind:'scatter',index:7,use:'두 수치의 관계와 예외 사례를 볼 때',avoid:'관련성이 곧 원인이라는 해석은 피하기'},{kind:'stacked',index:4,use:'반응 구성과 전체 규모를 함께 볼 때',avoid:'범주가 겹치는 자료를 부분의 합으로 그리지 않기'},{kind:'evidence',index:8,use:'원문·해석·반례를 함께 검토할 때',avoid:'단어 빈도로 경험의 중요도를 결정하지 않기'},{kind:'single',index:18,use:'기초선·중재 단계의 반복 측정을 볼 때',avoid:'단순 A–B 그림을 인과 효과의 증거로 쓰지 않기'},{kind:'radar',index:2,use:'동일 척도의 여러 준거를 한눈에 볼 때',avoid:'다른 단위 혼합 금지. 면적 크기로 우열 판단 금지'},{kind:'funnel',index:16,use:'같은 출발 집단의 단계별 도달을 볼 때',avoid:'서로 다른 집단을 이어 붙이지 않기'}];
const dirtyCSV='data_origin,student_id,week,emotion,score,context\nsynthetic,S01,1,걱정,2,발표 전\nsynthetic,S02,1,편안,4,짝 활동\nsynthetic,S03,1,속상,1,의견 충돌\nsynthetic,S01,2,편안,3,연습 후\nsynthetic,S02,2,편안,,짝 활동\nsynthetic,S03,2,걱정,6,발표 전\nsynthetic,S01,2,편안,3,연습 후';
export default function Home(){const [page,setPage]=useState(0);const [view,setView]=useState<'topics'|'room'|'workshop'>('topics');const [index,setIndex]=useState(9);const [tab,setTab]=useState('예시 화면');const [query,setQuery]=useState('');const [g,setG]=useState(0);const [modal,setModal]=useState('');const [notes,setNotes]=useState<Notes>({});const [links,setLinks]=useState<Notes>({menti:'https://www.mentimeter.com/',claude:'https://claude.ai/',padlet:PADLET_URL,github:'https://github.com/'});const [ready,setReady]=useState(false);const [done,setDone]=useState<number[]>([]);const [seconds,setSeconds]=useState(course[0].min*60);const [running,setRunning]=useState(false);const [answer,setAnswer]=useState(false);const [collect,setCollect]=useState('수집 설계');const reduce=useReducedMotion();const slide=course[page],d=designs[index];
 useEffect(()=>{try{const s=JSON.parse(localStorage.getItem('teacher-workshop-v2')||'{}');if(s.notes)setNotes(s.notes);if(s.links)setLinks(l=>({...l,...s.links,padlet:PADLET_URL}));if(s.done)setDone(s.done);if(Number.isInteger(s.index)&&s.index>=0&&s.index<topics.length)setIndex(s.index);}catch{}setReady(true)},[]);
 useEffect(()=>{if(ready)try{localStorage.setItem('teacher-workshop-v2',JSON.stringify({notes,links,done,index}));}catch{}},[notes,links,done,index,ready]);
 useEffect(()=>{setRunning(false);setSeconds(course[page].min*60)},[page]);
 useEffect(()=>{if(!running)return;const t=setInterval(()=>setSeconds(s=>{if(s<=1){setRunning(false);return 0}return s-1}),1000);return()=>clearInterval(t)},[running]);
 function go(n:number){setPage(Math.max(0,Math.min(course.length-1,n)));}
 function openCards(){setRunning(false);setView('topics');window.location.hash='topics';}
 function openRoom(i:number){setRunning(false);setIndex(i);setView('room');window.location.hash=`research/${i+1}`;}
 function openWorkshop(n=0){setPage(n);setView('workshop');window.location.hash='workshop';}
 useEffect(()=>{const sync=()=>{const hash=window.location.hash.slice(1);const match=hash.match(/^research\/(\d+)$/);if(match&&Number(match[1])>=1&&Number(match[1])<=topics.length){setIndex(Number(match[1])-1);setView('room');}else if(hash==='workshop'){setView('workshop');}else{setView('topics');}};sync();window.addEventListener('hashchange',sync);return()=>window.removeEventListener('hashchange',sync);},[]);
 useEffect(()=>{const key=(e:KeyboardEvent)=>{const el=e.target as HTMLElement;if(view!=='workshop'||modal||['INPUT','TEXTAREA','SELECT','BUTTON','SUMMARY'].includes(el.tagName)||el.isContentEditable)return;if(e.key==='ArrowRight'){e.preventDefault();setPage(p=>Math.min(14,p+1))}if(e.key==='ArrowLeft'){e.preventDefault();setPage(p=>Math.max(0,p-1))}};window.addEventListener('keydown',key);return()=>window.removeEventListener('keydown',key)},[modal,view]);
 const note=(key:string,label:string,placeholder:string,rows=3)=><label className='note-label'>{label}<textarea rows={rows} value={notes[key]||''} placeholder={placeholder} onChange={e=>setNotes({...notes,[key]:e.target.value})}/></label>;
 const tool=(key:string,label:string)=>links[key]&&/^https:\/\//.test(links[key])?<a className='btn' href={links[key]} target='_blank' rel='noopener noreferrer'><BrandLogo brand={brandForUrl(links[key])}/>{label}<ArrowUpRight size={16}/></a>:<button className='btn' onClick={()=>setModal('links')}><Link2 size={16}/>{label} 링크 넣기</button>;
 const exportNotes=()=>saveText(`# 마음을 데이터로, 데이터를 수업으로\n\n연구주제: ${topics[index].title}\n\n${Object.entries(notes).map(([k,v])=>`## ${k}\n${v}`).join('\n\n')}\n\n## 적용 전 확인\n모든 예시 데이터는 가상 자료입니다. 실제 연구의 척도·표집·분석계획은 연구자가 확정합니다.\n`, '나의-연수-실행기록.md');
 const buildPrompt=`${prompts(index)[3].body}\n이번에는 다음 수업에서 쓰는 기능 하나를 추가해줘. 교사가 목표, 활동 시간, 안내 문구를 수정할 수 있고, 학생은 선택–연습–성찰을 할 수 있게 해줘. 로그인·서버 저장·자동 위험 분류는 넣지 마. 빈 입력에는 이유를 설명하고, 키보드 조작과 큰 글씨를 지원해줘. 현재 데이터는 가상 자료만 사용해. GitHub Pages에 올릴 수 있도록 HTML·CSS·JavaScript가 담긴 단일 index.html 전체 파일로 줘. 빌드·서버·비밀키 없이 작동하게 해줘. 기능별 확인 방법 5개를 먼저 적고 구현해줘. 바꾼 코드와 수정 이유를 짧게 정리해줘.`;
 if(view!=='workshop')return <ResearchPortal view={view} index={index} onEnter={openRoom} onCards={openCards} onWorkshop={openWorkshop}/>;
 return <div className='app-shell'><header className='topbar'><button className='brand' onClick={openCards}><span className='brand-mark'><BookOpen size={20}/></span><span>RESEARCH STUDIO<small>연구년 교사 AI 실습</small></span></button><div className='header-actions'><PadletLink compact/><button onClick={openCards}><LayoutGrid size={17}/>연구주제 카드</button><button onClick={()=>openRoom(index)}>내 연구실<ArrowUpRight size={17}/></button><span className='duration'>50분 × 3차시 · 150분</span><button onClick={()=>setModal('slides')}><BookOpen size={17}/><span>강의안</span></button><button onClick={()=>setModal('sources')}><FileText size={17}/><span>근거 자료</span></button><button onClick={()=>setModal('links')} aria-label='실습 링크 설정'><Settings2 size={18}/></button></div></header>
 <nav className='chapter-nav' aria-label='연수 차례'>{chapters.map((c,i)=><button key={c} className={slide.chapter===i?'active':''} onClick={()=>go(course.findIndex(s=>s.chapter===i))}><span>{i+1}차시 · 50분</span>{c}</button>)}</nav>
 <main><div className='page-heading'><div><span className='eyebrow'>{slide.chapter+1}차시 · 50분 / {slide.name}</span><h1>{slide.title}</h1><p>{slide.sub}</p></div><div className='timer'><button onClick={()=>setRunning(!running)} aria-label={running?'타이머 일시정지':'타이머 시작'}>{running?<Pause size={16}/>:<Play size={16}/>}</button><span aria-live='off'>{Math.floor(seconds/60).toString().padStart(2,'0')}:{(seconds%60).toString().padStart(2,'0')}</span><button onClick={()=>{setRunning(false);setSeconds(slide.min*60)}} aria-label='타이머 초기화'><RotateCcw size={14}/></button></div></div>
 <AnimatePresence mode='wait'><motion.section key={page} className='page-content' initial={{opacity:0,x:reduce?0:18}} animate={{opacity:1,x:0}} exit={{opacity:0,x:reduce?0:-12}} transition={{duration:.23}}>
 {page===0&&<div className='split intro'><div className='panel intro-left'><span className='eyebrow'>오늘 가져갈 것</span><h2>내 질문에 맞는<br/>데이터와 화면 한 장.</h2><p>자료를 모으는 일부터 연구보고서까지,<br/>선생님의 주제로 직접 해봅니다.</p><div className='takeaways'><span>수집안</span><span>대시보드</span><span>수업 웹앱</span><span>실행 기록</span></div><button className='btn primary' onClick={()=>go(1)}>생각 모으기부터 <ArrowRight size={17}/></button><small>50분씩 3차시, 총 150분입니다. 차시 사이 쉬는 시간은 별도입니다.<br/>방향키 ← → 또는 아래 버튼으로 이동합니다.<br/>입력한 실습 메모는 이 브라우저에 저장됩니다.</small></div><div className='panel schedule'>{chapters.map((c,i)=>{const mins=course.filter(s=>s.chapter===i).reduce((a,s)=>a+s.min,0);return <button key={c} onClick={()=>go(course.findIndex(s=>s.chapter===i))}><span>0{i+1}</span><div><b>{c}</b><small>{['멘티미터 · 심스페이스 · 클래시파이 · Apps Script · 수업 사례','더미 데이터 점검 · 주제별 실습 · 차트 해석 · 제작 준비','Claude로 제작 · GitHub Pages 배포 · 보고서 TIP · 패들렛 공유'][i]}</small></div><em>{mins}분</em><ArrowUpRight size={17}/></button>})}</div></div>}
 {page===1&&<div className='split'><div className='panel'><span className='eyebrow'>MENTIMETER · 8분</span><h2>“내 연구에서<br/>확인하고 싶은 변화는?”</h2><p>워드클라우드에는 핵심어 3개, 이어지는 자유응답에는 연구 질문 한 문장을 적습니다.</p><Task n='01' title='2분 · 각자 적기'>예: 불안, 발화 시도, 자신감. 학생·학교 이름은 적지 않습니다.</Task><Task n='02' title='3분 · 비슷한 질문 묶기'>변화 확인 / 경험 이해 / 수업·도구 설계 중 어디에 가까운가요?</Task><Task n='03' title='3분 · 자료로 바꾸기'>“향상되는가?”를 “어떤 행동이 언제 달라지는가?”로 바꿔봅니다.</Task>{tool('menti','Mentimeter 열기')}</div><div className='panel tinted'><h3>나의 출발 질문</h3>{note('연구 질문','연구 질문 한 문장','예: 짝 말하기 활동 뒤 발표를 자발적으로 시도하는 학생이 늘어날까?',4)}{note('확인할 행동','눈으로 확인할 수 있는 행동','예: 발표 신청, 도움 요청, 근거를 덧붙인 발화',3)}<p className='small'>단어의 크기는 응답 빈도입니다. 중요도나 연구 효과를 뜻하지 않습니다.</p><SourceLinks ids={['menti']}/></div></div>}
 {page===2&&<div className='split'><div className='panel'><div className='flow-strip'>{['Tracing','Collection','Analysis','Communication'].map((v,i)=><div key={v}><span>0{i+1}</span><b>{v}</b><small>{['행동·지표 정의','자료 수집','양상 확인','수업 판단 공유'][i]}</small></div>)}</div><Task n='Q' title='배움의 흔적을 정합니다'>클릭 수를 볼까요, 학생의 설명을 볼까요? 연구 질문에 필요한 자료부터 정합니다.</Task><Task n='A' title='평균 옆에 맥락을 둡니다'>변화가 없는 사례와 예외를 지우지 않습니다. 학생의 설명과 관찰을 함께 봅니다.</Task><Task n='→' title='다음 수업까지 연결합니다'>그래프 아래에 “무엇을 더 확인하고 어떻게 가르칠지”를 남깁니다.</Task><SourceLinks ids={['solar','srl']}/></div><div className='panel tinted'><h3>교사에게 남는 판단</h3><p>AI는 표·코드·설명의 초안을 만듭니다. 측정할 개념, 근거의 적절성, 다음 수업은 교사가 결정합니다.</p><div className='list-lines'>{['인간 중심 사고','AI 윤리','AI 기초와 활용','AI 교수학습','AI를 통한 전문성 학습'].map((x,i)=><div key={x}><span>0{i+1}</span>{x}</div>)}</div><small>UNESCO 2024 · 5개 차원, 15개 역량<br/>강의안 3쪽의 네 영역에 전문성 학습을 함께 연결했습니다.</small><SourceLinks ids={['unesco']}/></div></div>}
 {page===3&&<div className='split'><div className='panel'><h2>체험 → 관찰 → 질문</h2><Task n='01' title='4분 · 학습자로 참여'>강사님이 안내한 심스페이스 활동에 참여합니다. 실제 학생 정보 대신 나의 오늘 상태나 가상 사례를 사용합니다.</Task><Task n='02' title='3분 · 화면 읽기'>입력한 내용 중 어떤 정보가 화면에 남았나요? 나의 상황을 설명하기에 부족한 정보는 무엇인가요?</Task><Task n='03' title='3분 · 교사의 추가 질문'>“이 점수는 왜 나왔지?” 대신 “어떤 상황이었는지 더 말해줄래?”를 연습합니다.</Task>{tool('sim','심스페이스 열기')}<p className='small'>서비스에 접속하지 못하면 다음 단계의 가상 체크인 CSV로 같은 활동을 할 수 있습니다.</p></div><div className='panel tinted'>{note('도구가 보여준 정보','도구에서 확인한 정보','예: 감정 선택, 기록 시점, 응답 내용')}{note('도구가 놓친 맥락','추가로 듣고 싶은 이야기','예: 어느 수업이었는지, 누구와 어떤 일이 있었는지')}{note('학생에게 할 질문','학생에게 물을 질문 하나','점수의 이유를 미리 정하지 않고 질문해봅니다.')}<div className='callout'>도구의 지표를 SEL 역량이나 임상적 진단과 동일하게 보지 않습니다.</div></div></div>}
 {page===4&&<div className='tabs' role='tablist' aria-label='데이터 수집 실습'>{['수집 설계','구글폼 만들기','Apps Script 수집앱','수집 화면 체험'].map(t=><button key={t} role='tab' aria-selected={collect===t} className={collect===t?'active':''} onClick={()=>setCollect(t)}>{t}</button>)}</div>}
 {page===4&&collect!=='수집 설계'&&<AppsScriptLab mode={collect} index={index} prompt={(title,body)=><Prompt title={title} body={body}/>} />}
 {page===4&&collect==='수집 설계'&&<div className='split'><div className='panel'><div className='section-row'><h3>사회정서 자료 수집안</h3>{tool('classify','클래시파이 시연')}</div><table><thead><tr><th>자료</th><th>수집 시점</th><th>해석에 필요한 것</th></tr></thead><tbody><tr><td>학생 체크인</td><td>수업 시작 · 짧게</td><td>선택한 감정, 상황, 응답 여부</td></tr><tr><td>관찰 기록</td><td>활동 중 · 같은 구간</td><td>행동, 맥락, 교사의 지원</td></tr><tr><td>성찰 문장</td><td>수업 직후</td><td>사용한 전략, 다음 계획</td></tr><tr><td>수행평가</td><td>활동 전·후</td><td>동일 준거, 원자료, 평정자</td></tr></tbody></table><h3 className='space-top'>같은 ‘걱정’도 다르게 읽기</h3><p>발표 직전의 일시적인 걱정과 여러 주에 걸친 수학 학습의 걱정은 추가로 확인할 내용이 다릅니다. 빈도만 보고 원인을 정하지 않습니다.</p><small>연결 강의안: Learning Analytics 5–6쪽</small><SourceLinks ids={['casel','privacy']}/></div><div className='panel tinted'><h3>어떤 자료를 모을까요?</h3>{note('수집 시점','시점과 빈도','예: 매주 화요일 1교시 시작 전, 6주')}{note('자료 수집 최소항목','꼭 필요한 항목','가명ID, 주차, 선택 감정, 상황 한 문장')}{note('자료 보관 계획','수집·보관·공유의 범위','누가 접근하고 언제 삭제할지 정합니다.')}<p className='small'>공개형 AI 실습에는 가상 자료를 사용합니다. 감정 선택을 긍정/부정 비율 하나로만 평가하지 않습니다.</p></div></div>}
 {page===5&&<div className='split'><div className='panel'><span className='eyebrow'>강사 사례 · 강의안 10–12, 18–20쪽</span><h2>마음 연습을<br/>수업 활동 안으로</h2><div className='flow-strip four'>{['멈춤','알아차림','조절','나눔'].map((x,i)=><div key={x}><span>0{i+1}</span><b>{x}</b><small>{['활동 전 체크인','몸·감정의 신호','전략 선택·연습','성찰과 다음 시도'][i]}</small></div>)}</div><p>프로젝트 수업과 체육 수업을 보며 “아이들이 실제로 연습한 기술”을 찾아봅니다. MOMO 사례에서는 교사가 바꿀 수 있는 목표와 활동에 주목합니다.</p>{tool('project','프로젝트 수업 사례')}{tool('momo','MOMO 사례')}<SourceLinks ids={['casel']}/></div><div className='panel tinted'><h3>SAFE로 수업 읽기</h3><Task n='S' title='순차성'>앞의 연습이 다음 활동으로 이어지는가?</Task><Task n='A' title='능동성'>학생이 직접 말하고 선택하고 해보는가?</Task><Task n='F' title='집중성'>한 가지 기술을 충분히 연습하는가?</Task><Task n='E' title='명시성'>무엇을 배우는지 학생도 알고 있는가?</Task>{note('내 수업에 가져올 활동','내 수업에 가져올 활동 하나','어떤 기술을 어떤 장면에서 연습하게 할까요?',2)}</div></div>}
 {page===6&&<div className='split'><div className='panel'><div className='section-row'><h3>체크인 CSV · 오류 찾기</h3><button className='btn' onClick={()=>saveText(dirtyCSV,'checkin-practice-synthetic.csv','text/csv;charset=utf-8')}><Download size={16}/> 더미 CSV</button></div><div className='code-table'><pre>{dirtyCSV}</pre></div><p>score는 1–5점입니다. 이름 대신 S01처럼 가상 ID를 씁니다. 중복·결측·범위 밖 값이 어디에 있나요?</p><button className='btn' onClick={()=>setAnswer(!answer)}>{answer?'해설 접기':'점검 결과 펼치기'}<ChevronDown size={16}/></button>{answer&&<div className='callout'>7행 중 중복 1행, 점수 결측 1행, 범위 밖 값(6점) 1행입니다. 중복 제거 후 6행에서 유효 점수는 4개, 평균은 2.5입니다. 사전·사후 모두 유효한 학생은 S01 한 명이므로 학급의 변화를 일반화할 수 없습니다.</div>}<small>심스페이스 실습을 이어가기 위한 별도 제작 자료입니다. 서비스의 실제 내보내기 형식은 아닙니다.</small></div><div className='panel tinted'><h3>집계 규칙을 먼저 적습니다</h3><Task n='01' title='한 행의 뜻'>학생 한 명의 한 주차 응답입니다. 학생 수와 기록 수를 구분합니다.</Task><Task n='02' title='제외한 이유'>완전 중복 1행만 제외합니다. 결측을 0으로 바꾸거나 범위 밖 값을 임의로 고치지 않습니다.</Task><Task n='03' title='차트와 표의 일치'>필터를 바꾸어도 유효 응답 수와 분모가 같이 바뀌는지 봅니다.</Task><Prompt title='데이터 점검 프롬프트' body={`이 CSV는 연수용 가상 체크인 자료야. 한 행은 학생×주차이고 score의 범위는 1~5야. 원자료를 보존하며 완전 중복, 결측, 범위 밖 값을 따로 표시해줘. 전체 기록 수·고유 학생 수·유효 점수 수·전후 짝 수를 각각 계산해줘. 중복 제거 후 범위 밖 값과 결측을 제외한 평균을 계산하되 0으로 대체하지 마. 제외 로그, 정리된 표와 전후 비교의 한계를 보여줘.\n\n${dirtyCSV}`}/></div></div>}
 {page===7&&<div className='split'><div className='panel'><span className='eyebrow'>주제별 실습</span><h2>자기 연구주제 카드로<br/>입장해주세요.</h2><p>연구실 안에 수집안부터 대시보드와 프롬프트까지 모아두었습니다. 지금 연수 흐름으로 돌아올 수도 있어요.</p><button className='btn primary' onClick={openCards}><LayoutGrid size={17}/> 연구주제 카드 열기</button></div><div className='panel tinted'><span className='eyebrow'>선택한 연구주제</span><h2>{d.short}</h2><p>{topics[index].title}</p><button className='btn' onClick={()=>openRoom(index)}>이 연구실로 입장 <ArrowRight size={17}/></button></div></div>}
 {page===8&&<div className='split gallery'><div className='panel'><span className='eyebrow'>CHART LIBRARY · 10가지</span><div className='chart-picks'>{gallery.map((a,i)=><button className={g===i?'selected':''} key={a.kind} onClick={()=>setG(i)}><span>{String(i+1).padStart(2,'0')}</span>{chartNames[a.kind]}</button>)}</div><h3>{gallery[g].use}</h3><p>{gallery[g].avoid}</p><button className='btn' onClick={()=>{setIndex(gallery[g].index);setTab('실습 프롬프트');openRoom(gallery[g].index)}}>이 예시의 프롬프트 <ArrowRight size={16}/></button></div><Dashboard key={g} index={gallery[g].index} override={gallery[g].kind}/></div>}
 {page===9&&<div className='split'><div><Dashboard index={index}/></div><div className='panel tinted'><h3>숫자에서 수업으로</h3>{note('관찰','1. 화면에서 확인한 사실','누구의 어떤 값이 얼마만큼 달라졌나요?',2)}{note('가능한 해석','2. 가능한 해석','“~일 가능성이 있다.” 다른 설명도 생각해봅니다.',2)}{note('추가 확인','3. 더 확인할 자료','학생의 설명, 관찰 메모, 참여 조건 중 무엇이 필요한가요?',2)}{note('다음 수업','4. 다음 수업에서 바꿀 것','활동·발문·지원 방식 중 한 가지를 정합니다.',2)}</div></div>}
 {page===10&&<div className='split'><div className='panel'><span className='eyebrow'>2차시 마무리 · 5분</span><h2>웹앱 제작 준비</h2><Task n='01' title='Claude와 GitHub 로그인'>계정 접속을 확인하고, 대시보드에 넣을 가상 CSV를 준비합니다.</Task><Task n='02' title='기능 하나 정하기'>누가 어떤 상황에서 어떤 버튼을 누를지 적습니다. 다음 차시에 index.html로 만들어 GitHub Pages에 올립니다.</Task>{tool('claude','Claude 열기')}{tool('github','GitHub 열기')}<p className='small'>차시 사이 쉬는 시간은 150분의 실습 시간에 포함하지 않습니다.</p></div><div className='panel tinted'>{note('만들 기능 하나','내 웹앱에 넣을 기능 하나','사용자 · 사용할 장면 · 버튼을 누른 뒤 나타날 결과',4)}<Prompt title='배포할 파일 형식 확인하기' body={githubExportPrompt}/></div></div>}
 {page===11&&<div className='split'><div className='panel'><h3>18분 안에 만드는 작은 앱</h3><Task n='01' title='3분 · 목표와 기능 정하기'>예: 감정을 고르면 조절 전략을 연습하고 성찰 한 문장을 남기는 도구. 교사가 안내 문구를 고칠 수 있게 합니다.</Task><Task n='02' title='10분 · Claude에 요청하기'>가상 CSV와 프롬프트를 넣고 실행 화면을 확인합니다. GitHub Pages에 올릴 단일 index.html을 요청하고 버튼과 계산을 직접 눌러봅니다.</Task><Task n='03' title='5분 · 하나씩 수정하기'>“더 좋게” 대신 “응답이 비어 있으면 저장하지 않고 안내 문구를 보여줘”처럼 바꿀 행동을 적습니다.</Task>{tool('claude','Claude 열기')}<p className='small'>현재 선택: {d.short} · 바꾸려면 대시보드 실습에서 다른 주제를 고르세요.</p></div><div className='panel tinted'><Prompt title='수업 웹앱 제작 프롬프트' body={buildPrompt}/><Prompt title='수정 요청 프롬프트' body='현재 웹앱에서 [어느 화면/버튼]을 [어떤 순서]로 누르면 [실제 결과]가 나와. 기대하는 결과는 [원하는 행동]이야. 원인을 설명하고 이 부분부터 고쳐줘. 정상 입력·빈 입력·경계값으로 수정 여부를 확인하고, 이전에 되던 기능이 유지되는지도 확인해줘.'/>{note('웹앱의 학습 목표','내 앱에서 연습할 기술','예: 갈등 상황에서 상대의 감정을 확인하는 질문 만들기',2)}{note('교사가 수정할 항목','교사가 바꿀 수 있어야 할 것','학년, 활동 시간, 상황 문장, 피드백',2)}<div className='callout'>실습 범위: 가상 데이터 · 브라우저에서 작동 · 로그인/서버 저장 없음. 기능을 늘리기보다 수업 의도를 확인합니다.</div></div></div>}
 {page===12&&<div className='split'><div className='panel'><h3>공유 전에 동료가 눌러봅니다</h3>{['아무것도 입력하지 않아도 화면이 깨지지 않는다.','범위 밖 점수와 중복 자료를 설명한다.','표의 5행과 차트의 값을 직접 대조했다.','작은 화면과 키보드로 핵심 기능을 쓸 수 있다.','학생 실명·원자료·비밀키가 코드에 없다.'].map((x,i)=><label className='check-item' key={x}><input type='checkbox' checked={notes['배포확인'+i]==='완료'} onChange={e=>setNotes({...notes,['배포확인'+i]:e.target.checked?'완료':''})}/>{x}</label>)}{note('수정 기록','오류 → 수정 이유 → 재확인','동료가 발견한 문제 하나와 고친 내용을 남깁니다.',3)}<Prompt title='동료 검토 프롬프트' body={prompts(index)[4].body}/></div><div className='panel tinted'><GitHubPublishLab/>{note('내 웹앱 주소','GitHub Pages 웹앱 주소','Settings → Pages → Visit site에서 복사한 주소',2)}<small>공유 후 동료의 계정·기기에서 실제 열리는지 확인합니다. 이 연수 페이지가 대신 배포해주는 기능은 아닙니다.</small></div></div>}
 {page===13&&<div className='split'><div className='panel'><h3>연구보고서의 네 부분</h3><Task n='01' title='방법: 누가, 언제, 무엇을'>대상·기간·자료·도구 버전·결측 처리·분석 절차를 재현할 수 있게 씁니다.</Task><Task n='02' title='결과: 확인한 것만'>표본 수·단위·차트의 원자료를 제시합니다. 결과 절에서는 원인을 미리 단정하지 않습니다.</Task><Task n='03' title='논의: 해석과 한계'>선행연구와 비교하고 대안 설명, 비교집단 부재, 작은 표본, 측정의 한계를 적습니다.</Task><Task n='04' title='부록: 판단의 흔적'>데이터 사전·코드북·프롬프트·검산표·교사 수정 이유·앱 변경 로그를 남깁니다.</Task><SourceLinks ids={['cos','wwc']}/></div><div className='panel tinted'><h3>표현을 한 번 고쳐봅시다</h3><div className='before-after'><small>과장된 문장</small><p>“AI 프로그램이 모든 학생의 정서 역량을 향상시켰다.”</p><small>자료에 맞춘 문장 틀</small><p>“분석에 포함된 __명의 __점수는 __에서 __로 변했다. 비교집단이 없어 이 변화를 프로그램만의 효과로 해석하기는 어렵다.”</p></div><Prompt title='보고서 작성·검토 프롬프트' body={`연구주제: ${topics[index].title}\n내가 제공한 분석표와 연구 메모만 근거로 방법–결과–논의의 초안을 작성해줘. 아직 제공하지 않은 표본 수, 수치, 인용, 유의확률은 [확인 필요]로 남겨줘. 관찰 사실과 해석을 나누고 인과 표현을 점검해줘. 가상 실습 데이터는 실제 연구 결과로 쓰지 마. 표와 그림 번호, 분석단위, 결측·제외 규칙을 확인할 목록을 붙여줘. AI 도구명·버전·사용일·사용 범위·교사 검토·수정 내역을 기록하는 부록 틀도 만들어줘.`}/>{note('AI 사용 기록','AI 사용·교사 수정 기록','도구/버전 · 사용일 · 맡긴 작업 · 내가 검토하고 고친 부분',3)}</div></div>}
 {page===14&&<div className='split'><div className='panel'><span className='eyebrow'>PAIR REVIEW · 5분</span><h2>이 그림으로<br/>무엇을 말할 수 있나요?</h2><Task n='01' title='질문과 자료가 맞나요?'>보여주는 지표가 연구 질문을 설명하는지 묻습니다.</Task><Task n='02' title='확인 못한 것은 무엇인가요?'>그림이 예쁘더라도 원자료·분모·맥락이 빠졌는지 봅니다.</Task><Task n='03' title='다음에는 무엇을 하나요?'>자료 수집, 도구 수정, 수업 실행 중 이번 주에 할 일 하나를 정합니다.</Task><button className='btn primary' onClick={exportNotes}><Download size={17}/> 내 실습 기록 내려받기</button><div className='share-result'><PadletLink/><small>만든 대시보드 링크나 화면을 올리고, 연구주제와 확인한 점을 함께 적어주세요.</small></div></div><div className='panel tinted'>{note('동료에게 받은 의견','동료에게 받은 의견','근거가 분명한 점 하나, 더 확인할 점 하나',3)}{note('이번 주 실행','이번 주 실행 한 가지','언제, 어떤 자료로, 무엇을 확인할지 적습니다.',3)}{note('성장 확인 방법','실행 뒤 확인할 증거','학생의 말, 수정본, 관찰 기록 중 무엇을 남길까요?',2)}<small>짝과 2분씩 의견을 나누고, 마지막 1분에 패들렛에 결과물을 올립니다. 이 기록은 현재 브라우저에 저장됩니다. 다른 기기로 옮기거나 수업을 마칠 때 파일로 내려받으세요.</small></div></div>}
 </motion.section></AnimatePresence></main>
 <footer className='footer'><button className='btn nav-btn' disabled={page===0} onClick={()=>go(page-1)}><ArrowLeft size={17}/> 이전</button><div className='page-dots'>{course.map((s,i)=><button key={s.name} title={s.name} aria-label={`${i+1} ${s.name}`} aria-current={i===page?'step':undefined} className={i===page?'current':done.includes(i)?'done':''} onClick={()=>go(i)}/>)}</div><button className={`complete ${done.includes(page)?'is-done':''}`} onClick={()=>setDone(done.includes(page)?done.filter(n=>n!==page):[...done,page])}><CheckCheck size={16}/>{done.includes(page)?'실습 완료':'완료 표시'}</button><span className='page-count'>{String(page+1).padStart(2,'0')} / 15</span><button className='btn primary nav-btn' disabled={page===14} onClick={()=>go(page+1)}>다음 <ArrowRight size={17}/></button></footer>
 {modal==='slides'&&<Modal title={`강의안 연결 · ${slide.name}`} onClose={()=>setModal('')}><div className='slide-viewer'><img src={`./slides/${slide.slide}.jpg`} alt={`${slide.slide.startsWith('la')?'Learning Analytics':'마음을 데이터로, 데이터를 수업으로'} ${slide.slide.split('-')[1]}쪽`}/><p>사용자 제공 강의안 · {slide.slide.startsWith('la')?'Learning Analytics':'마음을 데이터로, 데이터를 수업으로'} {slide.slide.split('-')[1]}쪽</p><div className='slide-picks'>{['la-1','la-2','la-3','la-4','la-5','la-6','sel-3','sel-7','sel-8','sel-9','sel-14','sel-15','sel-16','sel-17','sel-19','sel-20','sel-21'].map(s=><a key={s} href={`./slides/${s}.jpg`} target='_blank' rel='noreferrer'>{s.startsWith('la')?'학습분석':'마음'} {s.split('-')[1]}쪽<ExternalLink size={12}/></a>)}</div></div></Modal>}
 {modal==='sources'&&<Modal title='근거 자료와 적용 범위' onClose={()=>setModal('')}><p className='modal-intro'>공식 기관 원문을 중심으로 연결했습니다. 연구주제별 수집안과 차트는 제목을 바탕으로 제안한 설계이며, 검증된 연구 결과가 아닙니다. 확인일: 2026.09.19</p><div className='reference-cards all'>{references.map(r=><a key={r.id} href={r.url} target='_blank' rel='noreferrer'><span className='eyebrow'>{r.kind}</span><b>{r.title}<ArrowUpRight size={15}/></b><p>{r.note}</p></a>)}</div><div className='callout'>한국형 SEL·부산형 IB·학교자율시간의 세부 시행 지침은 적용 연도와 교육청 원문을 추가 확인해야 합니다. 원본 연구목록의 일부 모형 약어는 판독이 어려워 주제명에서 생략했습니다.</div></Modal>}
 {modal==='links'&&<Modal title='연수에서 사용할 링크' onClose={()=>setModal('')}><p className='modal-intro'>강사님의 실습방과 사례 주소를 넣어주세요. 이 브라우저에만 저장되며 참가자에게 자동 전송되지 않습니다.</p><div className='link-form'>{[['menti','Mentimeter 참여 또는 발표 주소'],['sim','심스페이스 실습방'],['classify','클래시파이 시연'],['project','프로젝트 수업 사례'],['momo','MOMO 사례'],['claude','Claude'],['padlet','Padlet 결과 공유방']].map(([k,v])=><label key={k}>{v}<input type='url' placeholder='https://…' value={links[k]||''} onChange={e=>setLinks({...links,[k]:e.target.value})}/>{links[k]&&!/^https:\/\//.test(links[k])&&<small className='error'>https://로 시작하는 주소를 넣어주세요.</small>}</label>)}</div><div className='section-row'><button className='btn' onClick={exportNotes}><Download size={16}/> 실습 기록 저장</button>{tool('padlet','Padlet 열기')}</div></Modal>}
 </div>;
}
