'use client';
import {useEffect,useState} from 'react';
import {ArrowLeft,ArrowRight,ArrowUpRight,BookOpen,Download,LayoutGrid,Search} from 'lucide-react';
import {motion,useReducedMotion} from 'motion/react';
import {topics} from './data';
import {designs,references,prompts,chartNames} from './workshop';
import {Dashboard,saveText} from './charts';
import {Prompt} from './practice-prompt';
import {PadletLink} from './service-links';
import {AppsScriptLab} from './apps-script-lab';
import {ResearchCard} from './research-card';
import {instructorIndex,instructorNotes} from './instructor-sample';
import {ResearchReport} from './research-report';
import ResearchMotionHero from '../components/ResearchMotionHero';

const steps=['연구 질문','수집 설계','수집 도구','정책·이론','대시보드','실습 프롬프트','연구보고서'];
type Records=Record<string,Record<string,string>>;
export function ResearchPortal({view,index,onEnter,onCards,onWorkshop}:{view:'topics'|'room';index:number;onEnter:(index:number)=>void;onCards:()=>void;onWorkshop:(page?:number)=>void}){
 const [colors,setColors]=useState<Record<string,string>>({});const [search,setSearch]=useState('');const [area,setArea]=useState('전체');const [cardPage,setCardPage]=useState(0);const [step,setStep]=useState(0);const [collection,setCollection]=useState('구글폼 만들기');const [records,setRecords]=useState<Records>({});const [ready,setReady]=useState(false);const reduce=useReducedMotion();
 useEffect(()=>{try{const stored=JSON.parse(localStorage.getItem('teacher-research-rooms-v1')||'{}');if(stored&&typeof stored==='object')setRecords(stored);}catch{}try{const raw=JSON.parse(localStorage.getItem('teacher-research-card-colors-v1')||'{}');if(raw&&typeof raw==='object'&&!Array.isArray(raw))setColors(Object.fromEntries(Object.entries(raw).filter(([,v])=>typeof v==='string'&&/^#[0-9a-f]{6}$/i.test(v))) as Record<string,string>);}catch{}setReady(true)},[]);
 useEffect(()=>{if(ready)try{localStorage.setItem('teacher-research-rooms-v1',JSON.stringify(records));}catch{}},[records,ready]);
 useEffect(()=>{if(ready)try{localStorage.setItem('teacher-research-card-colors-v1',JSON.stringify(colors));}catch{}},[colors,ready]);
 function changeColor(id:number,color?:string){setColors(old=>{const next={...old};if(color)next[id]=color;else delete next[id];return next;});}
 useEffect(()=>{setStep(0);setCollection('구글폼 만들기')},[index,view]);
 useEffect(()=>{const key=(e:KeyboardEvent)=>{const target=e.target as HTMLElement;if(['INPUT','TEXTAREA','SELECT','SUMMARY','BUTTON','A'].includes(target.tagName)||target.isContentEditable)return;if(view==='room'&&e.key==='ArrowRight'){e.preventDefault();setStep(v=>Math.min(steps.length-1,v+1))}if(view==='room'&&e.key==='ArrowLeft'){e.preventDefault();setStep(v=>Math.max(0,v-1))}};window.addEventListener('keydown',key);return()=>window.removeEventListener('keydown',key)},[view]);
 const matching=topics.map((t,i)=>({t,i})).filter(({t,i})=>!t.instructor&&(area==='전체'||t.area===area)&&(t.title+designs[i].short+t.area).toLowerCase().includes(search.trim().toLowerCase()));
 const pages=Math.max(1,Math.ceil(matching.length/4));const current=Math.min(cardPage,pages-1);const visible=matching.slice(current*4,current*4+4);const topic=topics[index],d=designs[index],ps=prompts(index);const memo={...(topic.instructor?instructorNotes:{}),...records[String(index)]};
 function changeNote(key:string,value:string){setRecords(r=>({...r,[String(index)]:{...r[String(index)],[key]:value}}))}
 function field(key:string,placeholder:string,rows=3){return <label className='note-label'>{key}<textarea rows={rows} value={memo[key]||''} placeholder={placeholder} onChange={e=>changeNote(key,e.target.value)}/></label>}

 function downloadRecord(){saveText(`# ${topic.title}\n\n## 연구질문\n${d.question}\n\n## 수집안\n분석 단위: ${d.unit}\n변수: ${d.fields}\n방법: ${d.sampling}\n\n## 예상 산출물\n${topic.output}\n\n${Object.entries(memo).map(([k,v])=>`## ${k}\n${v}`).join('\n\n')}\n\n## 근거 자료\n${d.refs.map(id=>references.find(r=>r.id===id)).filter(Boolean).map(r=>`- ${r!.title}: ${r!.url}`).join('\n')}\n\n※ 예시 화면은 가상 데이터입니다.\n`,`연구-${topic.id}-실습기록.md`)}
 return <div className={`app-shell portal-shell${topic.instructor&&view==='room'?' instructor-room':''}`}>
 <header className='topbar'><button className='brand' onClick={onCards}><span className='brand-mark'><BookOpen size={20}/></span><span>RESEARCH STUDIO<small>연구년 교사 AI 실습</small></span></button><div className='header-actions'><PadletLink compact/>{view==='room'&&<button onClick={onCards}><LayoutGrid size={17}/>연구주제 카드</button>}<button className='workshop-link' onClick={()=>onWorkshop(0)}><BookOpen size={17}/>공통 연수<ArrowUpRight size={15}/></button></div></header>
 {view==='topics'?<>
 <main className='portal-main'><ResearchMotionHero/><div className='portal-heading'><div><span className='eyebrow'>22개 실습 연구주제 + 강사 시연 1개</span><h1>선생님의 연구주제를 골라주세요.</h1><p>카드를 누르면 해당 주제의 데이터 수집안, 대시보드, 실습 프롬프트가 열립니다.</p></div><span className='portal-total'>{topics.length}<span>연구실</span></span></div>
 <ResearchCard topic={topics[instructorIndex]} short='마음데이터 웹앱 연구' onEnter={()=>onEnter(instructorIndex)} onColor={()=>{}}/>
 <div className='portal-controls'><label className='portal-search'><Search size={17}/><input aria-label='연구주제 검색' placeholder='연구주제 검색' value={search} onChange={e=>{setSearch(e.target.value);setCardPage(0)}}/></label><div className='area-filters' aria-label='연구 영역'>{['전체',...new Set(topics.filter(t=>!t.instructor).map(t=>t.area))].map(a=><button key={a} aria-pressed={area===a} className={area===a?'active':''} onClick={()=>{setArea(a);setCardPage(0)}}>{a}</button>)}</div></div>
 <p className='card-color-hint'>카드 아래에서 색을 고를 수 있어요. 선택한 색은 이 브라우저에 저장됩니다.</p>
 <div className='card-section' aria-label='연구주제 카드'><motion.div key={`${area}-${search}-${current}`} className='research-cards' initial={{opacity:0,x:reduce?0:12}} animate={{opacity:1,x:0}} transition={{duration:.2}}>{visible.map(({t,i})=><ResearchCard key={t.id} topic={t} short={designs[i].short} color={colors[t.id]} onColor={c=>changeColor(t.id,c)} onEnter={()=>onEnter(i)}/>)}</motion.div>{matching.length===0&&<div className='portal-empty'><Search size={25}/><h2>맞는 연구주제가 없어요.</h2><p>다른 낱말로 검색하거나 영역을 ‘전체’로 바꿔보세요.</p><button className='btn' onClick={()=>{setSearch('');setArea('전체');setCardPage(0)}}>전체 연구주제 보기</button></div>}</div>
 </main><footer className='footer portal-footer'><span className='portal-result'>연구주제 {matching.length}개{matching.length>0&&` · ${current*4+1}–${Math.min((current+1)*4,matching.length)}번째`}</span><div className='card-pagination'><button className='btn' disabled={current===0} onClick={()=>setCardPage(current-1)}><ArrowLeft size={16}/>이전 카드</button><div className='card-page-buttons'>{Array.from({length:pages},(_,i)=><button key={i} aria-label={`카드 ${i+1}페이지`} aria-current={i===current?'page':undefined} className={i===current?'active':''} onClick={()=>setCardPage(i)}>{i+1}</button>)}</div><button className='btn primary' disabled={current>=pages-1} onClick={()=>setCardPage(current+1)}>다음 카드<ArrowRight size={16}/></button></div></footer>
 </>:<>
 <div className='room-breadcrumb'><button onClick={onCards}>연구주제 카드</button><span>/</span><strong>{d.short}</strong><span className='room-area'>{topic.area} · {topic.track}</span></div>
 <main className='room-main'><div className='room-heading'><span className='room-number'>{topic.instructor?'DEMO':String(topic.id).padStart(2,'0')}</span><div><span className='eyebrow'>나의 연구실</span><h1>{d.short}</h1><p>{topic.title}</p></div></div>
 {topic.instructor&&<div className='instructor-notice'><b>두목쿼카 · 강사 시연 연구실</b><span>선생님들과 같은 1~7단계입니다. 입력된 계획·자료·보고서는 모두 가상 시연 예시이며 자유롭게 수정할 수 있어요.</span></div>}
 <nav className='room-steps' aria-label='내 연구실 실습 단계'>{steps.map((s,i)=><button key={s} className={step===i?'active':''} aria-current={step===i?'step':undefined} onClick={()=>setStep(i)}><span>{i+1}</span>{s}</button>)}</nav>
 <motion.section key={`${index}-${step}`} className='page-content room-content' initial={{opacity:0,x:reduce?0:12}} animate={{opacity:1,x:0}} transition={{duration:.18}}>
 {step===0&&<div className='split room-overview'><div className='panel room-question'><span className='eyebrow'>이 연구에서 확인할 것</span><h2>{d.question}</h2><p>{topic.lab}</p><div className='room-output'><small>예상 산출물</small><h3>{topic.output}</h3></div><button className='btn primary' onClick={()=>setStep(1)}>수집할 데이터 정하기<ArrowRight size={17}/></button></div><div className='panel tinted'><h3>이 연구실에서 할 일</h3><div className='room-path'>{[['자료 수집',d.unit+' 단위로 기록',1],['대시보드',chartNames[d.chart]+' 예시 보기',4],['실습 프롬프트','이 주제로 작성된 프롬프트 5개',5],['연구보고서','공식 양식의 목차별 보고서 작성',6]].map(([title,desc,dest])=><button key={String(title)} onClick={()=>setStep(Number(dest))}><div><b>{title}</b><small>{desc}</small></div><ArrowUpRight size={17}/></button>)}</div><p className='small'>연구주제에 맞춰 제안한 실습안입니다. 표집과 척도는 실제 연구계획에 맞게 확정해주세요.</p></div></div>}
 {step===1&&<div className='split'><div className='panel'><h2>수집할 데이터</h2><dl><dt>한 행의 단위</dt><dd>{d.unit}</dd><dt>수집할 열</dt><dd>{d.fields}</dd><dt>시점·방법</dt><dd>{d.sampling}</dd><dt>확인할 지표</dt><dd>{d.metric}</dd></dl><div className='callout'>{topic.caution}</div></div><div className='panel tinted'><Prompt {...ps[0]}/>{field('나의 수집 계획','대상·기간·자료·수집 시점을 적어보세요.',4)}{field('수집 전에 확인할 것','척도 출처, 문항, 자료 보관 범위 등',3)}<button className='btn' onClick={()=>setStep(2)}>구글폼·Apps Script 실습<ArrowRight size={16}/></button></div></div>}
 {step===2&&<><div className='room-tool-tabs'>{['구글폼 만들기','Apps Script 수집앱','수집 화면 체험'].map(v=><button key={v} className={collection===v?'active':''} onClick={()=>setCollection(v)}>{v}</button>)}</div><AppsScriptLab mode={collection} index={index} prompt={(title,body)=><Prompt title={title} body={body}/>}/></>}
 {step===3&&<div className='split'><div className='panel'><h2>관련 정책과 이론</h2><p>{d.theory}</p><div className='reference-cards'>{[...d.refs,'privacy'].map(id=>{const r=references.find(ref=>ref.id===id)!;return <a key={id} href={r.url} target='_blank' rel='noreferrer'><span className='eyebrow'>{r.kind}</span><b>{r.title}<ArrowUpRight size={16}/></b><p>{r.note}</p></a>})}</div></div><div className='panel tinted'><Prompt {...ps[1]}/>{field('내 연구에 적용할 근거','원문에서 확인한 주장·쪽수·적용 범위·한계를 기록하세요.',5)}<small>국제 권고, 국내 정책, 연구 이론은 구분해서 읽습니다. 원문을 확인하지 못한 항목은 미확인으로 남깁니다.</small></div></div>}
 {step===4&&<div className='split room-dashboard'><div><Dashboard key={index} index={index}/><p className='insight'>가상 데이터 예시입니다. CSV에는 이 차트의 표시값이 들어 있습니다.</p></div><div className='panel tinted'><span className='eyebrow'>내 연구의 예상 화면</span><h2>{chartNames[d.chart]}</h2><p>{d.action}</p><Prompt {...ps[2]}/><Prompt {...ps[3]}/><Prompt {...ps[4]}/>{field('이 화면으로 확인할 것','관찰한 사실과 더 확인할 자료를 구분해 적습니다.',2)}</div></div>}
 {step===5&&<div className='split'><div className='panel'><h2>{d.short}<br/>실습 프롬프트</h2><p>수집안을 정한 뒤 근거를 확인하고, 가상 자료로 대시보드를 만듭니다. 필요한 단계만 펼쳐 복사하세요.</p><div className='room-output'><small>분석 단위</small><h3>{d.unit}</h3><small>예상 산출물</small><h3>{topic.output}</h3></div><button className='btn' onClick={()=>setStep(2)}>이 주제의 수집 도구 만들기<ArrowRight size={16}/></button></div><div>{ps.map(p=><Prompt key={`${index}-${p.title}`} {...p}/>)}</div></div>}
 {step===6&&<ResearchReport key={topic.id} topic={topic} design={d} memo={memo} onChange={changeNote} onDownloadNotes={downloadRecord}/>}
 </motion.section></main>
 <footer className='footer room-footer'><button className='btn' onClick={onCards}><LayoutGrid size={16}/>주제 카드로</button><span className='room-footer-topic'>{String(topic.id).padStart(2,'0')} · {d.short}</span><div className='room-paging'><button className='btn' disabled={step===0} onClick={()=>setStep(step-1)}><ArrowLeft size={16}/>이전</button><span>{step+1} / {steps.length}</span><button className='btn primary' disabled={step===steps.length-1} onClick={()=>setStep(step+1)}>다음<ArrowRight size={16}/></button></div></footer>
 </>}
 </div>
}
